In [1]:
import pandas as pd

In [2]:
customer_data = pd.read_csv("../Data/Processed/customers_cleaned.csv")
order_data = pd.read_csv("../Data/Processed/orders_cleaned.csv")
order_items_data = pd.read_csv("../Data/Processed/order_items_cleaned.csv")

In [3]:
customer_data["customer_state"].unique()

<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [4]:
# How many total customers are there?
Total_customers=customer_data["customer_unique_id"].count() #repeat customers also included
Unique_customers=customer_data["customer_unique_id"].nunique()
print(f"The total customers is:-",Total_customers)
print(f"The unique customers is:-",Unique_customers)

# There are 99,441 customer records representing 96,096 unique customers, indicating that some customers placed multiple orders.

The total customers is:- 99441
The unique customers is:- 96096

In [5]:
# How many unique customer states are there?
state_unique_customers=customer_data.groupby("customer_state")[
["customer_unique_id"]
    ].nunique().sort_values("customer_unique_id",ascending=False)
state_unique_customers

# SP state has the largest customer base without any repeated customers all the customers here is unique mean no customer is repeated among all the 
# state so they will provide some discounts and offers to their customers so that the customers start purchasing the products repeatedly and their sales
# will became increased and rr state has the lower unique customer base they will improve their marketing and logistic strategies,understand their customers problems
# to improve their sells
# Problem:-The dataset tells you how many customers are there, but it doesn't tell you why SP has more customers.You cannot conclude that SP has more 
# customers because of marketing, discounts or logistics.

# Better interpretation:- São Paulo has by far the largest customer base, while Roraima has the smallest. This indicates a highly concentrated customer
# distribution, with São Paulo representing the most important market by customer volume. However, customer count alone does not explain the underlying
# reasons for this geographic concentration.

                customer_unique_id
customer_state
SP                           40302
RJ                           12384
MG                           11259
RS                            5277
PR                            4882
SC                            3534
BA                            3277
DF                            2075
ES                            1964
GO                            1952
PE                            1609
CE                            1313
PA                             949
MT                             876
MA                             726
MS                             694
PB                             519
PI                             482
RN                             474
AL                             401
SE                             342
TO                             273
RO                             240
AM                             143
AC                              77
AP                              67
RR                              45

In [6]:
# How many customers are there in each state?
state_customer_count=customer_data.groupby("customer_state")[
["customer_unique_id"]
    ].count().sort_values("customer_unique_id",ascending=False)
state_customer_count

# SP state has the largest repeated customer base among all the state it mean it has more loyal customers then any others states as customers like 
# their marketing and logistic strategies and it may be possible that customers also like their discount and offers and rr state has the lower repeated
# customer base they will improve their marketing and logistic strategies,understand their customers problems to improve their sells and attract more 
# loyal customers
# That conclusion is incorrect:- A larger number of customer records does not mean more loyalty.SP has a larger customer base. That's all this analysis proves.
# Loyalty requires looking at repeat customers / repeat purchase rate.

# Correct interpretation:-São Paulo has the largest customer record volume, while Roraima has the smallest. However, customer volume should not be 
# interpreted as customer loyalty; loyalty should be measured using repeat-purchase behavior.

                customer_unique_id
customer_state
SP                           41746
RJ                           12852
MG                           11635
RS                            5466
PR                            5045
SC                            3637
BA                            3380
DF                            2140
ES                            2033
GO                            2020
PE                            1652
CE                            1336
PA                             975
MT                             907
MA                             747
MS                             715
PB                             536
PI                             495
RN                             485
AL                             413
SE                             350
TO                             280
RO                             253
AM                             148
AC                              81
AP                              68
RR                              46

In [7]:
# Which state has the highest number of customers?
Highest_customer_state=customer_data.groupby("customer_state")[
    ["customer_unique_id"]
    ].nunique().sort_values("customer_unique_id",ascending=False)#.head(1)

Highest_customer_state

                customer_unique_id
customer_state
SP                           40302
RJ                           12384
MG                           11259
RS                            5277
PR                            4882
SC                            3534
BA                            3277
DF                            2075
ES                            1964
GO                            1952
PE                            1609
CE                            1313
PA                             949
MT                             876
MA                             726
MS                             694
PB                             519
PI                             482
RN                             474
AL                             401
SE                             342
TO                             273
RO                             240
AM                             143
AC                              77
AP                              67
RR                              45

In [8]:
# What are the top 10 cities by customer count
Top_10_customer_city=customer_data.groupby("customer_city")[
    ["customer_unique_id"]
    ].nunique().sort_values("customer_unique_id",ascending=False).head(10)

Total_customers=customer_data["customer_unique_id"].nunique()
# Total_customers
Top_10_customer_city["customers_concentration"]=Top_10_customer_city["customer_unique_id"]/Total_customers*100
Top_10_customer_city


# # São Paulo has the highest number of unique customers and represents approximately 15% of the total unique customer base. This indicates that the 
# customer base is highly concentrated in São Paulo, making it the dominant customer market.

                       customer_unique_id  customers_concentration
customer_city
sao paulo                           14984                15.592741
rio de janeiro                       6620                 6.888944
belo horizonte                       2672                 2.780553
brasilia                             2069                 2.153055
curitiba                             1465                 1.524517
campinas                             1398                 1.454795
porto alegre                         1326                 1.379870
salvador                             1209                 1.258117
guarulhos                            1153                 1.199842
sao bernardo do campo                 908                 0.944888

In [9]:
customer_with_orders=customer_data.merge(
    order_data[["customer_id","order_id","order_status"]],
    on="customer_id",
    how="left"
)
customer_with_orders

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered
...,...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered

In [10]:
# How many unique customers made only one purchase?

order_per_customer=customer_with_orders.groupby("customer_unique_id")[
["order_id"]
    ].nunique()
print(order_per_customer.value_counts())

One_purchase_customer=order_per_customer[order_per_customer==1].count().unique()
print(One_purchase_customer)

# repeat_customer=order_per_customer[order_per_customer>1].sum().unique()
# print(repeat_customer) #6342

# Most of the orders purchased by customer only at one time so to increased the sell we have to change the marketing strategies in such a way that the
# customers start purchasing products or placed orders more then one time

order_id
1           93099
2            2745
3             203
4              30
5               8
6               6
7               3
9               1
17              1
Name: count, dtype: int64
[93099]

In [11]:
# How many customers are repeat customers?

repeat_customer=(order_per_customer>1).sum()
print(repeat_customer)

order_id    2997
dtype: int64

In [12]:
# What is the repeat-customer rate?
repeat_customer_rate=repeat_customer/Total_customers*100
repeat_customer_rate

# out of 100 there is only 3% repeat customers rate so to increased the sales and profit our future goal can be to increased the customer retention and also 
# considered other factors also along with this

order_id    3.118756
dtype: float64

In [13]:
# What is the average number of orders per customer?
Avg_customer_orders=customer_with_orders.groupby("customer_unique_id")[
["order_id"]
    ].nunique()
Avg_customer_orders.mean()

order_id    1.034809
dtype: float64

In [14]:
customer_order_revenue=customer_with_orders.merge(
    order_items_data[["order_id","price","freight_value"]],
    on="order_id",
    how="left"
)
customer_order_revenue

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,230.00,22.25
...,...,...,...,...,...,...,...,...,...
113420,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,74.90,13.88
113421,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,114.90,14.16
113422,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,37.00,19.04
113423,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,689.00,22.07
113424,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,13.99,7.78

In [15]:
# What is the revenue generated by customers in each state?
State_customer_revenue=(
    customer_order_revenue.groupby("customer_state")
.agg(
customer_count=("customer_unique_id","nunique"),
Revenue=("price","sum")
)
)
State_customer_revenue.sort_values(["customer_count","Revenue"],ascending=False)

# SP state contribute to generate the highest revenue because its has high customer base and rr generate the lowest revenue as it customer base is low
# so rr has to change its marketing,logistic startegies and build a new strategies that will attract more customers such as giving some discounts ,
# offers ,free gifts or gift vouchers ets as customer count along is not responsible for the revenue generation other factors also play an inportant 
# role such as Revenue can depend on number of customers,purchase frequency,average order value,product mix etc

                customer_count     Revenue
customer_state
SP                       40302  5202955.05
RJ                       12384  1824092.67
MG                       11259  1585308.03
RS                        5277   750304.02
PR                        4882   683083.76
SC                        3534   520553.34
BA                        3277   511349.99
DF                        2075   302603.94
ES                        1964   275037.31
GO                        1952   294591.95
PE                        1609   262788.03
CE                        1313   227254.71
PA                         949   178947.81
MT                         876   156453.53
MA                         726   119648.22
MS                         694   116812.64
PB                         519   115268.08
PI                         482    86914.08
RN                         474    83034.98
AL                         401    80314.81
SE                         342    58920.85
TO                         273    49621.74
RO                         240    46140.64
AM                         143    22356.84
AC                          77    15982.95
AP                          67    13474.30
RR                          45     7829.43

In [16]:
# Which state has the highest average revenue per customer?

Revenue_per_customer=(
    customer_order_revenue
        .groupby(["customer_unique_id","customer_state"])
["price"].sum().reset_index()
)
# print(Revenue_per_customer)

state_avg_revenue=(
    Revenue_per_customer
    .groupby("customer_state")
        ["price"].mean().sort_values(ascending=False)
)
# print(state_avg_revenue)
customer_order_revenue
# This tell us something interesting as pb state although generate less revenue by its total customer base but its avg revenue per customer is 
# high as each customer spend more money on individual products.This indicates that customers in Paraíba spend more on average than customers in other
# states. This makes PB an interesting market for customer-value analysis.

# reset index converts customer_unique_id and customer_state back into columns, and price remains a column.

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,230.00,22.25
...,...,...,...,...,...,...,...,...,...
113420,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,74.90,13.88
113421,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,114.90,14.16
113422,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,37.00,19.04
113423,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,689.00,22.07
113424,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,13.99,7.78

In [17]:
# Which customers generated the highest revenue?
Highest_revenue_customer=customer_order_revenue.groupby("customer_unique_id")[
    ["price"]
    ].sum()
Highest_revenue_customer.sort_values("price",ascending=False).head(1)

                                    price
customer_unique_id
0a0a92112bd4c708ca5fde585afaa872  13440.0

In [18]:
# Which state has the highest number of repeat customers?
order_per_customer = (
    customer_with_orders
        .groupby(["customer_unique_id", "customer_state"])["order_id"]
        .count()
        .reset_index()
)

repeat_customer = order_per_customer[
    order_per_customer["order_id"] > 1
]

# Repeat customers by state
state_repeat_customer = (
    repeat_customer
        .groupby("customer_state")["customer_unique_id"]
        .nunique()
)

# Total customers by state
total_customer_state = (
    customer_with_orders
        .groupby("customer_state")["customer_unique_id"]
        .nunique()
)

# One table
state_repeat_customer = (
    pd.DataFrame({
        "repeat_customer": state_repeat_customer,
        "repeat_customer_rate": (
            state_repeat_customer / total_customer_state * 100
        )
    })
    .sort_values("repeat_customer", ascending=False)
)

state_repeat_customer.sort_values(["repeat_customer","repeat_customer_rate"],ascending=False)

## sp state has higest no of repeat customers which tells that its marketing and logistic strategy is good as they understand the customer need very 
# well while rr has lowest repeat customers as they have to work on their strategies and try to understand the customer needs.
# Problem:- You wrote that this proves:SP's marketing and logistics strategy is good.It does not prove that There could be many reasons:
# larger population,greater ecommerce adoption,urbanization,income differences,product availability,customer acquisition,geography

# Better conclusion:-São Paulo has the largest absolute number of repeat customers, reflecting its much larger customer base. To assess loyalty fairly
# across states, repeat-customer rate should be compared rather than absolute repeat-customer count.

                repeat_customer  repeat_customer_rate
customer_state
SP                         1296              3.215721
RJ                          421              3.399548
MG                          338              3.002043
RS                          167              3.164677
PR                          145              2.970094
SC                           95              2.688172
BA                           93              2.837962
GO                           64              3.278689
DF                           62              2.987952
ES                           57              2.902240
PE                           33              2.050963
MT                           29              3.310502
PA                           24              2.528978
CE                           22              1.675552
MS                           18              2.593660
MA                           17              2.341598
PB                           13              2.504817
AL                           12              2.992519
RN                           11              2.320675
PI                           11              2.282158
RO                           10              4.166667
SE                            8              2.339181
TO                            7              2.564103
AC                            4              5.194805
AM                            3              2.097902
RR                            1              2.222222
AP                            1              1.492537

In [19]:
# Compare customer count, order count, and revenue by state.
customer_comparison=(customer_order_revenue.groupby("customer_state")
    .agg(
    customer_count=("customer_unique_id","nunique"),
    order_count=("order_id","nunique"),
    revenue=("price","sum")
)
                    )
customer_comparison.sort_values(["customer_count","order_count","revenue"],ascending=False)
# it clearly tell that sp state has more numbers of customers that is why the order placed is also more and the sells is also high,while rr has lower
# customer base low order placed and lowest sells.However, this table alone does not prove that the higher customer count causes the higher order 
# volume and revenue.This shows a strong association between customer base size, order volume, and total revenue across states.

                customer_count  order_count     revenue
customer_state
SP                       40302        41746  5202955.05
RJ                       12384        12852  1824092.67
MG                       11259        11635  1585308.03
RS                        5277         5466   750304.02
PR                        4882         5045   683083.76
SC                        3534         3637   520553.34
BA                        3277         3380   511349.99
DF                        2075         2140   302603.94
ES                        1964         2033   275037.31
GO                        1952         2020   294591.95
PE                        1609         1652   262788.03
CE                        1313         1336   227254.71
PA                         949          975   178947.81
MT                         876          907   156453.53
MA                         726          747   119648.22
MS                         694          715   116812.64
PB                         519          536   115268.08
PI                         482          495    86914.08
RN                         474          485    83034.98
AL                         401          413    80314.81
SE                         342          350    58920.85
TO                         273          280    49621.74
RO                         240          253    46140.64
AM                         143          148    22356.84
AC                          77           81    15982.95
AP                          67           68    13474.30
RR                          45           46     7829.43

In [21]:
# What is the average delivery time by customer state?

order_customer=order_data.merge(
    customer_data[["customer_id","customer_unique_id","customer_state"]],
    on="customer_id",
    how="left"
)
date_columns = [
    "order_purchase_timestamp",
    "order_delivered_customer_date"
]

order_customer[date_columns] = (
    order_customer[date_columns]
    .apply(pd.to_datetime, format="mixed")
)
order_customer["delivery_time"]=(order_customer["order_delivered_customer_date"]-order_customer["order_purchase_timestamp"]).dt.days
avg_delivery_time=order_customer.groupby("customer_state")[
["delivery_time"]
    ].mean()
avg_delivery_time.sort_values("delivery_time",ascending=False)

# RR state take more number of days to delivered the orders to the customers while sp state delivered order faster.The relationship between delivery 
# speed and customer volume/revenue would require further analysis before claiming that faster delivery causes higher customer retention or revenue.

# "SP has both a larger customer base and faster delivery times; further analysis is required to determine whether delivery performance contributes 
# to customer retention."

                delivery_time
customer_state
RR                  28.975610
AP                  26.731343
AM                  25.986207
AL                  24.040302
PA                  23.316068
MA                  21.117155
SE                  21.029851
CE                  20.817826
AC                  20.637500
PB                  19.953578
PI                  18.993697
RO                  18.913580
BA                  18.866400
RN                  18.824895
PE                  17.966102
MT                  17.593679
TO                  17.226277
ES                  15.331830
MS                  15.191155
GO                  15.151763
RJ                  14.849510
RS                  14.819611
SC                  14.480124
DF                  12.509135
MG                  11.544694
PR                  11.527321
SP                   8.298481